package GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;

import javax.swing.JCheckBox;
import javax.swing.JRadioButton;

/**
 *
 * @author MikeBednarski
 * Version 1: September 24, 2019
 * This is the GUI frame for the Disney Emoji Blitz category chooser. Given up to 3 categories
 * or one box and 2 categories, this will give what emojis fulfill the categories chosen.
 * 
 */
public class DEBCatFrame extends javax.swing.JFrame implements ItemListener, ActionListener {

	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form DEBCatFrame
	 */
	public DEBCatFrame() {
		categories = new ArrayList<String>();
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	private void initComponents() {

		buttonGroup = new javax.swing.ButtonGroup();
		GroupLabel = new javax.swing.JLabel();
		Aladdin = new javax.swing.JCheckBox();
		Alice_in_Wonderland = new javax.swing.JCheckBox();
		Animal = new javax.swing.JCheckBox();
		Bearded = new javax.swing.JCheckBox();
		Beauty_and_the_Beast = new javax.swing.JCheckBox();
		BigEared = new javax.swing.JCheckBox();
		Blue = new javax.swing.JCheckBox();
		Boys = new javax.swing.JCheckBox();
		Cat_or_Dog = new javax.swing.JCheckBox();
		Coco = new javax.swing.JCheckBox();
		Finding_NemoDory = new javax.swing.JCheckBox();
		Flying = new javax.swing.JCheckBox();
		FourLegged = new javax.swing.JCheckBox();
		Frozen = new javax.swing.JCheckBox();
		Girls = new javax.swing.JCheckBox();
		Green = new javax.swing.JCheckBox();
		Hatwearing = new javax.swing.JCheckBox();
		Haunted_Mansion = new javax.swing.JCheckBox();
		Hercules = new javax.swing.JCheckBox();
		Inside_Out = new javax.swing.JCheckBox();
		Jewelry = new javax.swing.JCheckBox();
		Mickey_and_Friends = new javax.swing.JCheckBox();
		Moana = new javax.swing.JCheckBox();
		Monsters_Inc = new javax.swing.JCheckBox();
		Mulan = new javax.swing.JCheckBox();
		Nightmare_Before_Christmas = new javax.swing.JCheckBox();
		Orange = new javax.swing.JCheckBox();
		Outer_Space = new javax.swing.JCheckBox();
		Pirates_of_the_Caribbean = new javax.swing.JCheckBox();
		Pixar = new javax.swing.JCheckBox();
		Pocahontas = new javax.swing.JCheckBox();
		Prince = new javax.swing.JCheckBox();
		Princess_and_the_Frog = new javax.swing.JCheckBox();
		Princesses = new javax.swing.JCheckBox();
		Purple = new javax.swing.JCheckBox();
		Red = new javax.swing.JCheckBox();
		Rescue_Rangers = new javax.swing.JCheckBox();
		Scary = new javax.swing.JCheckBox();
		Sleeping_Beauty = new javax.swing.JCheckBox();
		Snow_White = new javax.swing.JCheckBox();
		Star_Wars = new javax.swing.JCheckBox();
		Tangled = new javax.swing.JCheckBox();
		The_Incredibles = new javax.swing.JCheckBox();
		The_Jungle_Book = new javax.swing.JCheckBox();
		The_Lion_King = new javax.swing.JCheckBox();
		The_Little_Mermaid = new javax.swing.JCheckBox();
		The_Muppets = new javax.swing.JCheckBox();
		Toy_Story = new javax.swing.JCheckBox();
		Underwater = new javax.swing.JCheckBox();
		Up = new javax.swing.JCheckBox();
		Winnie_the_Pooh = new javax.swing.JCheckBox();
		Yellow = new javax.swing.JCheckBox();
		BoxLabel = new javax.swing.JLabel();
		ExecuteButton = new javax.swing.JButton();
		Silver = new javax.swing.JRadioButton();
		Gold = new javax.swing.JRadioButton();
		Rainbow = new javax.swing.JRadioButton();
		Series = new javax.swing.JRadioButton();
		Villain = new javax.swing.JRadioButton();
		None = new javax.swing.JRadioButton();
        Information = new javax.swing.JLabel();


		buttonGroup.add(Silver);
		buttonGroup.add(Gold);
		buttonGroup.add(Rainbow);
		buttonGroup.add(Series);
		buttonGroup.add(Villain);
		buttonGroup.add(None);
		None.setSelected(true);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Disney Emoji Blitz Categories");
		getContentPane().setBackground(new java.awt.Color(132, 112, 187));

		GroupLabel.setForeground(new java.awt.Color(211, 211, 211));
		GroupLabel.setText("Groups");

        Aladdin.setForeground(new java.awt.Color(255, 255, 255));
		Aladdin.setText("Aladdin");
		Aladdin.setName("Aladdin");
		Aladdin.addItemListener(this);

		Alice_in_Wonderland.setForeground(new java.awt.Color(255, 255, 255));
		Alice_in_Wonderland.setText("Alice in Wonderland");
		Alice_in_Wonderland.setName("Alice_in_Wonderland");
		Alice_in_Wonderland.addItemListener(this);

		Animal.setForeground(new java.awt.Color(255, 255, 255));
		Animal.setText("Animal");
		Animal.setName("Animal");
		Animal.addItemListener(this);

		Bearded.setForeground(new java.awt.Color(255, 255, 255));
		Bearded.setText("Bearded");
		Bearded.setName("Bearded");
		Bearded.addItemListener(this);

		Beauty_and_the_Beast.setForeground(new java.awt.Color(255, 255, 255));
		Beauty_and_the_Beast.setText("Beauty and the Beast");
		Beauty_and_the_Beast.setName("Beauty_and_the_Beast");
		Beauty_and_the_Beast.addItemListener(this);

		BigEared.setForeground(new java.awt.Color(255, 255, 255));
		BigEared.setText("Big Eared");
		BigEared.setName("BigEared");
		BigEared.addItemListener(this);

		Blue.setForeground(new java.awt.Color(255, 255, 255));
		Blue.setText("Blue");
		Blue.setName("Blue");
		Blue.addItemListener(this);

		Boys.setForeground(new java.awt.Color(255, 255, 255));
		Boys.setText("Boys");
		Boys.setName("Boys");
		Boys.addItemListener(this);

		Cat_or_Dog.setForeground(new java.awt.Color(255, 255, 255));
		Cat_or_Dog.setText("Cat or Dog");
		Cat_or_Dog.setName("Cat_or_Dog");
		Cat_or_Dog.addItemListener(this);
		
		Coco.setForeground(new java.awt.Color(255, 255, 255));
		Coco.setText("Coco");
		Coco.setName("Coco");
		Coco.addItemListener(this);

		Finding_NemoDory.setForeground(new java.awt.Color(255, 255, 255));
		Finding_NemoDory.setText("Finding Nemo/Dory");
		Finding_NemoDory.setName("Finding_NemoDory");
		Finding_NemoDory.addItemListener(this);

		Flying.setForeground(new java.awt.Color(255, 255, 255));
		Flying.setText("Flying");
		Flying.setName("Flying");
		Flying.addItemListener(this);

		FourLegged.setForeground(new java.awt.Color(255, 255, 255));
		FourLegged.setText("Four Legged");
		FourLegged.setName("FourLegged");
		FourLegged.addItemListener(this);

		Frozen.setForeground(new java.awt.Color(255, 255, 255));
		Frozen.setText("Frozen");
		Frozen.setName("Frozen");
		Frozen.addItemListener(this);

		Girls.setForeground(new java.awt.Color(255, 255, 255));
		Girls.setText("Girls");
		Girls.setName("Girls");
		Girls.addItemListener(this);

		Green.setForeground(new java.awt.Color(255, 255, 255));
		Green.setText("Green");
		Green.setName("Green");
		Green.addItemListener(this);

		Hatwearing.setForeground(new java.awt.Color(255, 255, 255));
		Hatwearing.setText("Hat Wearing");
		Hatwearing.setName("Hatwearing");
		Hatwearing.addItemListener(this);

		Haunted_Mansion.setForeground(new java.awt.Color(255, 255, 255));
		Haunted_Mansion.setText("Haunted Mansion");
		Haunted_Mansion.setName("Haunted_Mansion");
		Haunted_Mansion.addItemListener(this);

		Hercules.setForeground(new java.awt.Color(255, 255, 255));
		Hercules.setText("Hercules");
		Hercules.setName("Hercules");
		Hercules.addItemListener(this);

		Inside_Out.setForeground(new java.awt.Color(255, 255, 255));
		Inside_Out.setText("Inside Out");
		Inside_Out.setName("Inside_Out");
		Inside_Out.addItemListener(this);

		Jewelry.setForeground(new java.awt.Color(255, 255, 255));
		Jewelry.setText("Jewelry");
		Jewelry.setName("Jewelry");
		Jewelry.addItemListener(this);

		Mickey_and_Friends.setForeground(new java.awt.Color(255, 255, 255));
		Mickey_and_Friends.setText("Mickey and Friends");
		Mickey_and_Friends.setName("Mickey_and_Friends");
		Mickey_and_Friends.addItemListener(this);

		Moana.setForeground(new java.awt.Color(255, 255, 255));
		Moana.setText("Moana");
		Moana.setName("Moana");
		Moana.addItemListener(this);

		Monsters_Inc.setForeground(new java.awt.Color(255, 255, 255));
		Monsters_Inc.setText("Monsters, Inc.");
		Monsters_Inc.setName("Monsters_Inc");
		Monsters_Inc.addItemListener(this);

		Mulan.setForeground(new java.awt.Color(255, 255, 255));
		Mulan.setText("Mulan");
		Mulan.setName("Mulan");
		Mulan.addItemListener(this);

		Nightmare_Before_Christmas.setForeground(new java.awt.Color(255, 255, 255));
		Nightmare_Before_Christmas.setText("Nightmare Before Christmas");
		Nightmare_Before_Christmas.setName("Nightmare_Before_Christmas");
		Nightmare_Before_Christmas.addItemListener(this);

		Orange.setForeground(new java.awt.Color(255, 255, 255));
		Orange.setText("Orange");
		Orange.setName("Orange");
		Orange.addItemListener(this);

		Outer_Space.setForeground(new java.awt.Color(255, 255, 255));
		Outer_Space.setText("Outer Space");
		Outer_Space.setName("Outer_Space");
		Outer_Space.addItemListener(this);

		Pirates_of_the_Caribbean.setForeground(new java.awt.Color(255, 255, 255));
		Pirates_of_the_Caribbean.setText("Pirates of the Caribbean");
		Pirates_of_the_Caribbean.setName("Pirates_of_the_Caribbean");
		Pirates_of_the_Caribbean.addItemListener(this);

		Pixar.setForeground(new java.awt.Color(255, 255, 255));
		Pixar.setText("Pixar");
		Pixar.setName("Pixar");
		Pixar.addItemListener(this);

		Pocahontas.setForeground(new java.awt.Color(255, 255, 255));
		Pocahontas.setText("Pocahontas");
		Pocahontas.setName("Pocahontas");
		Pocahontas.addItemListener(this);

		Prince.setForeground(new java.awt.Color(255, 255, 255));
		Prince.setText("Prince");
		Prince.setName("Prince");
		Prince.addItemListener(this);

		Princess_and_the_Frog.setForeground(new java.awt.Color(255, 255, 255));
		Princess_and_the_Frog.setText("Princess and the Frog");
		Princess_and_the_Frog.setName("Princess_and_the_Frog");
		Princess_and_the_Frog.addItemListener(this);

		Princesses.setForeground(new java.awt.Color(255, 255, 255));
		Princesses.setText("Princesses");
		Princesses.setName("Princesses");
		Princesses.addItemListener(this);

		Purple.setForeground(new java.awt.Color(255, 255, 255));
		Purple.setText("Purple");
		Purple.setName("Purple");
		Purple.addItemListener(this);

		Red.setForeground(new java.awt.Color(255, 255, 255));
		Red.setText("Red");
		Red.setName("Red");
		Red.addItemListener(this);

		Rescue_Rangers.setForeground(new java.awt.Color(255, 255, 255));
		Rescue_Rangers.setText("Rescue Rangers");
		Rescue_Rangers.setName("Rescue_Rangers");
		Rescue_Rangers.addItemListener(this);

		Scary.setForeground(new java.awt.Color(255, 255, 255));
		Scary.setText("Scary");
		Scary.setName("Scary");
		Scary.addItemListener(this);

		Sleeping_Beauty.setForeground(new java.awt.Color(255, 255, 255));
		Sleeping_Beauty.setText("Sleeping Beauty");
		Sleeping_Beauty.setName("Sleeping_Beauty");
		Sleeping_Beauty.addItemListener(this);

		Snow_White.setForeground(new java.awt.Color(255, 255, 255));
		Snow_White.setText("Snow White");
		Snow_White.setName("Snow_White");
		Snow_White.addItemListener(this);

		Star_Wars.setForeground(new java.awt.Color(255, 255, 255));
		Star_Wars.setText("Star Wars");
		Star_Wars.setName("Star_Wars");
		Star_Wars.addItemListener(this);

		Tangled.setForeground(new java.awt.Color(255, 255, 255));
		Tangled.setText("Tangled");
		Tangled.setName("Tangled");
		Tangled.addItemListener(this);

		The_Incredibles.setForeground(new java.awt.Color(255, 255, 255));
		The_Incredibles.setText("The Incredibles");
		The_Incredibles.setName("The_Incredibles");
		The_Incredibles.addItemListener(this);

		The_Jungle_Book.setForeground(new java.awt.Color(255, 255, 255));
		The_Jungle_Book.setText("The Jungle Book");
		The_Jungle_Book.setName("The_Jungle_Book");
		The_Jungle_Book.addItemListener(this);
		
		The_Lion_King.setForeground(new java.awt.Color(255, 255, 255));
		The_Lion_King.setText("The Lion King");
		The_Lion_King.setName("The_Lion_King");
		The_Lion_King.addItemListener(this);

		The_Little_Mermaid.setForeground(new java.awt.Color(255, 255, 255));
		The_Little_Mermaid.setText("The Little Mermaid");
		The_Little_Mermaid.setName("The_Little_Mermaid");
		The_Little_Mermaid.addItemListener(this);

		The_Muppets.setForeground(new java.awt.Color(255, 255, 255));
		The_Muppets.setText("The Muppets");
		The_Muppets.setName("The_Muppets");
		The_Muppets.addItemListener(this);

		Toy_Story.setForeground(new java.awt.Color(255, 255, 255));
		Toy_Story.setText("Toy Story");
		Toy_Story.setName("Toy_Story");
		Toy_Story.addItemListener(this);

		Underwater.setForeground(new java.awt.Color(255, 255, 255));
		Underwater.setText("Underwater");
		Underwater.setName("Underwater");
		Underwater.addItemListener(this);

		Up.setForeground(new java.awt.Color(255, 255, 255));
		Up.setText("Up");
		Up.setName("Up");
		Up.addItemListener(this);

		Winnie_the_Pooh.setForeground(new java.awt.Color(255, 255, 255));
		Winnie_the_Pooh.setText("Winnie the Pooh");
		Winnie_the_Pooh.setName("Winnie_the_Pooh");
		Winnie_the_Pooh.addItemListener(this);

		Yellow.setForeground(new java.awt.Color(255, 255, 255));
		Yellow.setText("Yellow");
		Yellow.setName("Yellow");
		Yellow.addItemListener(this);

		BoxLabel.setForeground(new java.awt.Color(211, 211, 211));
		BoxLabel.setText("Boxes");

		ExecuteButton.setText("Execute");
		ExecuteButton.setEnabled(false);
		ExecuteButton.addActionListener(this);

		Silver.setForeground(new java.awt.Color(191, 193, 195));
		Silver.setText("Silver");
		Silver.setName("Silver");
		Silver.addActionListener(this);

		Gold.setForeground(new java.awt.Color(240, 189, 92));
		Gold.setText("Gold");
		Gold.setName("Gold");
		Gold.addActionListener(this);

		Rainbow.setForeground(new java.awt.Color(102, 178, 112));
		Rainbow.setText("Rainbow");
		Rainbow.setName("Rainbow");
		Rainbow.addActionListener(this);

		Series.setForeground(new java.awt.Color(153, 222, 191));
		Series.setText("Series");
		Series.setName("Series");
		Series.addActionListener(this);

		Villain.setForeground(new java.awt.Color(250, 230, 250));
		Villain.setText("Villain");
		Villain.setName("Villain");
		Villain.addActionListener(this);

		None.setForeground(new java.awt.Color(255, 255, 255));
		None.setText("None");
		None.setName("None");
		None.addActionListener(this);
		

		Information.setForeground(new java.awt.Color(250, 128, 114));
        Information.setText("Requirements: Up to 3 Groups or 1 Box + Up to 2 Groups");
        
		setResizable(false);


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Aladdin)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Alice_in_Wonderland)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Animal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Bearded)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Beauty_and_the_Beast))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(GroupLabel)
                                        .addGap(89, 89, 89)))
                                .addComponent(BigEared)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Blue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Boys)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Cat_or_Dog))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Coco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Finding_NemoDory)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Flying)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FourLegged)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Frozen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Girls)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Green)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Hatwearing)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Haunted_Mansion))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Hercules)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Inside_Out)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Jewelry)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Mickey_and_Friends)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Moana)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Monsters_Inc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Mulan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Nightmare_Before_Christmas))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Orange)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Outer_Space)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pirates_of_the_Caribbean)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pixar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pocahontas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Prince)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Princess_and_the_Frog)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Princesses))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Purple)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Red)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Rescue_Rangers)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Scary)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Sleeping_Beauty)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Snow_White)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Star_Wars)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Tangled)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(The_Incredibles))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(The_Jungle_Book)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(The_Lion_King)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(The_Little_Mermaid)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(The_Muppets)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Toy_Story)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Underwater)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Up)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Winnie_the_Pooh))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Yellow)
                                .addGap(362, 362, 362)
                                .addComponent(BoxLabel))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(411, 411, 411)
                        .addComponent(ExecuteButton)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Information))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(Silver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Gold)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Rainbow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Series, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Villain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(None)))
                .addGap(265, 265, 265))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GroupLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aladdin)
                    .addComponent(Alice_in_Wonderland)
                    .addComponent(Animal)
                    .addComponent(Bearded)
                    .addComponent(Beauty_and_the_Beast)
                    .addComponent(BigEared)
                    .addComponent(Blue)
                    .addComponent(Boys)
                    .addComponent(Cat_or_Dog))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Coco)
                    .addComponent(Finding_NemoDory)
                    .addComponent(Flying)
                    .addComponent(FourLegged)
                    .addComponent(Frozen)
                    .addComponent(Girls)
                    .addComponent(Green)
                    .addComponent(Hatwearing)
                    .addComponent(Haunted_Mansion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hercules)
                    .addComponent(Inside_Out)
                    .addComponent(Jewelry)
                    .addComponent(Mickey_and_Friends)
                    .addComponent(Moana)
                    .addComponent(Monsters_Inc)
                    .addComponent(Mulan)
                    .addComponent(Nightmare_Before_Christmas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Orange)
                    .addComponent(Outer_Space)
                    .addComponent(Pirates_of_the_Caribbean)
                    .addComponent(Pixar)
                    .addComponent(Pocahontas)
                    .addComponent(Prince)
                    .addComponent(Princess_and_the_Frog)
                    .addComponent(Princesses))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Purple)
                    .addComponent(Red)
                    .addComponent(Rescue_Rangers)
                    .addComponent(Scary)
                    .addComponent(Sleeping_Beauty)
                    .addComponent(Snow_White)
                    .addComponent(Star_Wars)
                    .addComponent(Tangled)
                    .addComponent(The_Incredibles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(The_Jungle_Book)
                    .addComponent(The_Lion_King)
                    .addComponent(The_Little_Mermaid)
                    .addComponent(The_Muppets)
                    .addComponent(Toy_Story)
                    .addComponent(Underwater)
                    .addComponent(Up)
                    .addComponent(Winnie_the_Pooh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Yellow)
                    .addComponent(BoxLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Silver)
                    .addComponent(Gold)
                    .addComponent(Rainbow)
                    .addComponent(Series)
                    .addComponent(Villain)
                    .addComponent(None))
                .addGap(18, 18, 18)
                .addComponent(Information)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(ExecuteButton))
        );

		pack();
	}

	public void itemStateChanged(ItemEvent e) {
		JCheckBox check = (JCheckBox) e.getSource();
		if (check.isSelected())
			categories.add(check.getName());
		else
			categories.remove(check.getName());
		buttonStatus();

	}

	public void actionPerformed(ActionEvent e) {
		if (e.getSource() instanceof JRadioButton) {
			JRadioButton rbName = (JRadioButton) e.getSource();
			boxToSearch = rbName.getName();
			buttonStatus();
		} else {
			ArrayList<String> finalCats = new ArrayList<String>(categories);
			if (!boxToSearch.equals("None"))
				finalCats.add(boxToSearch);
			Results rs = new Results();
			rs.setUp(finalCats);
		}
	}

	private void buttonStatus() {
		if (boxToSearch.equals("None")) {
			if (categories.size() > 3 || categories.isEmpty())
				ExecuteButton.setEnabled(false);
			else
				ExecuteButton.setEnabled(true);
		} else {
			if (categories.size() > 2)
				ExecuteButton.setEnabled(false);
			else
				ExecuteButton.setEnabled(true);

		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */

		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException
				| javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DEBCatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}


		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> {
			new DEBCatFrame().setVisible(true);
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JCheckBox Aladdin;
	private javax.swing.JCheckBox Alice_in_Wonderland;
	private javax.swing.JCheckBox Animal;
	private javax.swing.JCheckBox Bearded;
	private javax.swing.JCheckBox Beauty_and_the_Beast;
	private javax.swing.JCheckBox BigEared;
	private javax.swing.JCheckBox Blue;
	private javax.swing.JLabel BoxLabel;
	private javax.swing.JCheckBox Boys;
	private javax.swing.JCheckBox Cat_or_Dog;
	private javax.swing.JCheckBox Coco;
	private javax.swing.JButton ExecuteButton;
	private javax.swing.JCheckBox Finding_NemoDory;
	private javax.swing.JCheckBox Flying;
	private javax.swing.JCheckBox FourLegged;
	private javax.swing.JCheckBox Frozen;
	private javax.swing.JCheckBox Girls;
	private javax.swing.JRadioButton Gold;
	private javax.swing.JCheckBox Green;
	private javax.swing.JLabel GroupLabel;
	private javax.swing.JCheckBox Hatwearing;
	private javax.swing.JCheckBox Haunted_Mansion;
	private javax.swing.JCheckBox Hercules;
    private javax.swing.JLabel Information;
	private javax.swing.JCheckBox Inside_Out;
	private javax.swing.JCheckBox Jewelry;
	private javax.swing.JCheckBox Mickey_and_Friends;
	private javax.swing.JCheckBox Moana;
	private javax.swing.JCheckBox Monsters_Inc;
	private javax.swing.JCheckBox Mulan;
	private javax.swing.JCheckBox Nightmare_Before_Christmas;
	private javax.swing.JRadioButton None;
	private javax.swing.JCheckBox Orange;
	private javax.swing.JCheckBox Outer_Space;
	private javax.swing.JCheckBox Pirates_of_the_Caribbean;
	private javax.swing.JCheckBox Pixar;
	private javax.swing.JCheckBox Pocahontas;
	private javax.swing.JCheckBox Prince;
	private javax.swing.JCheckBox Princess_and_the_Frog;
	private javax.swing.JCheckBox Princesses;
	private javax.swing.JCheckBox Purple;
	private javax.swing.JRadioButton Rainbow;
	private javax.swing.JCheckBox Red;
	private javax.swing.JCheckBox Rescue_Rangers;
	private javax.swing.JCheckBox Scary;
	private javax.swing.JRadioButton Series;
	private javax.swing.JRadioButton Silver;
	private javax.swing.JCheckBox Sleeping_Beauty;
	private javax.swing.JCheckBox Snow_White;
	private javax.swing.JCheckBox Star_Wars;
	private javax.swing.JCheckBox Tangled;
	private javax.swing.JCheckBox The_Incredibles;
	private javax.swing.JCheckBox The_Jungle_Book;
	private javax.swing.JCheckBox The_Lion_King;
	private javax.swing.JCheckBox The_Little_Mermaid;
	private javax.swing.JCheckBox The_Muppets;
	private javax.swing.JCheckBox Toy_Story;
	private javax.swing.JCheckBox Underwater;
	private javax.swing.JCheckBox Up;
	private javax.swing.JRadioButton Villain;
	private javax.swing.JCheckBox Winnie_the_Pooh;
	private javax.swing.JCheckBox Yellow;
	private javax.swing.ButtonGroup buttonGroup;
	ArrayList<String> categories;
	ArrayList<String> boxes;
	String boxToSearch = "None";
	// End of variables declaration

}
